### ISSUE TITLE
[!] Error installing VoiceItApi2IosSDK

### ISSUE THREAD

**Issue by yo2bh** [voiceittech/VoiceIt2-IosSDK#1]
[!] Error installing VoiceItApi2IosSDK
[!] /usr/bin/git clone https://github.com/voiceittech/VoiceItApi2IosSDK.git /var/folders/ct/zz6hd21x1yg82wmg66f79vt9lbzwt1/T/d20200624-31204-aj93y7 --template= --single-branch --depth 1 --branch 2.0.9

Cloning into '/var/folders/ct/zz6hd21x1yg82wmg66f79vt9lbzwt1/T/d20200624-31204-aj93y7'...
warning: Could not find remote branch 2.0.9 to clone.
fatal: Remote branch 2.0.9 not found in upstream origin

**Comment by noeljgrover** [comment]
Please pull now. It has been addressed.
